### ISSUE TITLE
Get rid of too many logs generated from `println` 

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-DataLake#3]
Currently, there are too many `println` methods used through the project (e.g. [here](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/Run.scala). See [here](https://github.com/SANSA-Stack/SANSA-DataLake/issues/1#issuecomment-461777050) how the output looks at the moment.
It is always good to have such information for academic purposes but for other users, it would be nicer if we skip these logs (at least on the console) while running the SANSA-Query DataLake API. 
The best option could be to use [Logger](https://www.slf4j.org/) and disable the logs by default. In case there is a need for logs, users can set logger to *INFO* (see [this](https://github.com/SANSA-Stack/SANSA-Inference/blob/develop/sansa-inference-common/src/main/scala/net/sansa_stack/inference/utils/Logging.scala) as one of the examples how to do it).

Best regards,

**Comment by mnmami** [comment]
This was fixed by this [commit](https://github.com/SANSA-Stack/SANSA-DataLake/commit/354e5d3aeeedd1afb52c2c2d0fa7f9aa2b809dd2).
Now only the query to be executed, first 20 lines of the results, number of results as well as the time taken by the query engine. To enable the detailed logging the logging level should be set to `INFO` in `log4j.properties` file.
