### ISSUE TITLE
Parsing JSON to RDF using RML. Is it possible ?

### ISSUE THREAD

**Issue by justgfather** [SANSA-Stack/SANSA-DataLake#7]
I read in the sansa-lake documentation that it uses RML mapping. However, when it lists the different datasources on this page: https://github.com/SANSA-Stack/SANSA-Query/tree/develop/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/datalake . JSON is not part of it? My questions is: Can Sansa convert a JSON file into an rdf turtle file using RML mapping.

Thank you

**Comment by mnmami** [comment]
Hi @justgfather sorry for the delay, holidays!

>  JSON is not part of it?

No, at the moment plain JSON files are not supported. We might support JSON in the future, but if you need to use SANSA-DataLake features now, then you have the possibility to import JSON files into MongoDB, which is supported.

> Can Sansa convert a JSON file into an rdf turtle file using RML mapping.

Assuming here that you are still questioning about SANSA-DataLake, then that is also not possible. SANSA-DataLake queries original data sources, it does not "physically" convert any data to any format.

If you are interested in obtaining RDF data AND you are a developer, you can rather simply extend SANSA-DataLake code to allow generating RDF data. This is because we are using Spark DataFrames (under property graph scheme), which can be saved to disk. For example, if you want to save the final results of the query to disk in RDF, then that can be done from here: [https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/Run.scala#L290](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/Run.scala#L290)

**Comment by mnmami** [comment]
Closing this now. SANSA does not convert JSON file or any other format to RDF.
